//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SavaKursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empolee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Adress { get; set; }
        public int PositionId { get; set; }
        public string PassportNum { get; set; }
        public int SubjectId { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
