//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SavaKursach
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStage
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int StageId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
